kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: microk8s-hostpath
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
